export interface IPartnerOwnIslandItem{
    id: number,
    name: string,
    location: string,
    description: string,
    size: number,
    price: number,
    imageUrl: string,
    fileType: string,
    islandRegionId: number,
    islandRegionName: string,
    populationSizeId: number,
    populationSizeName: string,
    isPublic: boolean,
}